Updated to python ^3.8 & Pillow ^9.5
consbio/mapservice-clientlib pull request #3
Opened 2023-06-28 20:51 UTC by jesudasjoseph

2023-06-28 20:53 UTC, nikmolnar approved these changes

2023-06-28 20:53 UTC, nikmolnar requested changes
Make sure to update the dependency in `setup.py` as well.

2023-06-28 20:54 UTC, nikmolnar commented
> Make sure to update the dependency in `setup.py` as well.

https://github.com/consbio/mapservice-clientlib/blob/main/setup.py#L37

2023-06-28 20:58 UTC, jesudasjoseph commented
> Make sure to update the dependency in `setup.py` as well.

Updated.

2023-06-29 17:39 UTC, nikmolnar approved these changes

2023-06-29 18:21 UTC, merged